name: News Scraper
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python scraper.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'News Bot'
          git config --global user.email 'bot@github.com'
          git add news_feed.json
          git commit -m "Update live news" || exit 0
          git push
